# Site settings
title: Jason Huff
email: jsnhff@gmail.com
description: "Fun testing"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jason-huff.com" # the base hostname & protocol for your site
twitter_username: jsnhff
github_username:  jsnhff

# Build settings
markdown: kramdown
